version: '3.8'

services:
  frontend:
    build: .                  # uses the Dockerfile in current folder
    container_name: my-app
    ports:
      - "8080:80"             # access app at http://localhost:8080
    restart: unless-stopped

